# run roles
- hosts: all
  tags: base
  become: true
  #gater_facts: true
  pre_tasks:
    - name: Gather Facts
      setup:

  roles:
    - base
   
   tasks:
   
     - name: Display facts
       set_fact:
         output:
           hostname: "{{ ansible_hostname }}"
           distro: "{{ ansible_distribution }}"
           version: "{{ ansible_distribution_version }}"
           runkernel: "{{ ansible_kernel }}"
           grublist: "{{ grub_table }}"
           etcgrub: " {{ etc_grub_exists }}"
           grubver: "{{ grub_version }}"
           grubdef: "{{ grub_default }}"

     - set_fact:
         combined_output: "{{ output | to_json }}"
      #delegate_to: localhost
      #run_once: yes

     - name: Output JSON file
       copy:
         dest: "/tmp/output.json"
         content: "{{ combined_output }}"
     #delegate_to: localhost
       become: no
     #run_once: yes

     - name: EMAIL BACKUPS
       community.general.mail:
         host: smtp.nrc.ca
         port: 25
         subject: Ansible-report
         body: Hello, this is an e-mail. I hope you like it ;-)
         from: ansiblenrc@ssc-spc.gc.ca (Brian Beckwith)
         to:
           - brian.beckwith@ssc-spc.gc.ca
         attach:
           - /tmp/output.json
        #headers: 'Reply-To=john@example.com|X-Special="Something or other"'
        #        charset: utf8
        # delegate_to: localhost
       become: no
      # run_once: True
