
# run roles
- hosts: all
  tags: base
  become: true
  #gater_facts: true
  pre_tasks:
    - name: Gather Facts
      setup:
    
    - name: Check for previous output.json file
      stat:
        path: /srv/output.json
      register: pre_output
    
    - set_fact:
        check_sum: "{{ pre_output.stat.checksum | default(false)}}"
    
    - debug:
        var: check_sum
        
  roles:
    - base
   
  tasks:
   
    - name: Display facts
      set_fact:
        output:
          hostname: "{{ ansible_hostname }}"
          distro: "{{ ansible_distribution }}"
          version: "{{ ansible_distribution_version }}"
          runkernel: "{{ ansible_kernel }}"
          grublist: "{{ grub_table }}"
          etcgrub: " {{ etc_grub_exists }}"
          grubver: "{{ grub_version }}"
          grubdef: "{{ grub_default }}"

    - set_fact:
        combined_output: "{{ output | to_json }}"
      
    - name: Output JSON file
      copy:
        dest: "/srv/output.json"
        content: "{{ combined_output }}"
      become: no

    - name: Check new checksum
      stat:
        path: /srv/output.json
      register: cur_check_sum  


    - name: EMAIL BACKUPS
      community.general.mail:
        host: smtp.nrc.ca
        port: 25
        subject: Ansible-report
        body: Hello, this is an e-mail. I hope you like it ;-)
        from: ansiblenrc@ssc-spc.gc.ca (Brian Beckwith)
        to:
          - brian.beckwith@ssc-spc.gc.ca
        attach:
          - /srv/output.json
      become: no
      when: check_sum != cur_check_sum.stat.checksum 
        

