- name: users | beck | add public key
  tags: dotfiles,ssh,ssh-keys,users
  authorized_key:
    user: beck
    key: "{{ lookup('file', 'users/beck/ssh/authorized_keys') }}"
    state: present
    exclusive: true
  
