- name: gather facts
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Gather facts
      setup:

- block:
  # Make sure users exist on the system
  - import_tasks: grub_kernel/grub-info.yml

  rescue:
    - set_fact: task_failed=true
